package com.dkorobtsov.veriff.website.test.constants

const val EPIC_VERIFF_WEBSITE = "Veriff Website"

const val FEATURE_HYPERLINKS_VALIDATION = "Hyperlinks validation"
const val STORY_NEGATIVE_CHECKS = "Negative test"
const val STORY_VISUAL_CHECK = "Visual Check"
const val STORY_NAVIGATION = "Navigation"
const val STORY_SEARCH = "Search"
const val STORY_STATUS_CODE_CHECK = "Status Code Check"
const val STORY_REDIRECT_CHECK = "Redirect Check"

const val FEATURE_FORGOT_PASSWORD = "Forgot Password Page"
const val FEATURE_CONTACT_SALES = "Contact Sales Page"
const val FEATURE_CASE_STUDIES = "Case Studies Page"
const val FEATURE_DEVELOPERS = "Developers Page"
const val FEATURE_SUPPORT = "Support Page"
const val FEATURE_CAREERS = "Careers Page"
const val FEATURE_COMPANY = "Company Page"
const val FEATURE_PRODUCT = "Product Page"
const val FEATURE_MAIN_PAGE = "Main Page"
const val FEATURE_LOGIN = "Login Page"
const val FEATURE_VERIFF_TIMES = "Veriff Times"
const val FEATURE_PRIVACY_POLICY = "Privacy Policy"
const val FEATURE_TERMS_AND_CONDITIONS = "Terms and Conditions"
const val FEATURE_RESPONSIBLE_DISCLOSURE = "Responsible Disclosure"
